config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web, at: "/sidekiq"


  get 'calender/index'
  ActiveAdmin.routes(self)
  namespace :admin do
    resource :graphs, only: [:show]
  end
  root to: 'groups#index'
  get 'signup', to: 'users#new'
  #resources :tasks
  resources :users, only: [:new, :create]
  resources :groups, shallow: true do
    resources :tasks
    resources :custom_task_lists, only: [:index] do
      put :sort
    end
    resources :members
    resources :calenders, only: [:index]
  end
  resource :plofile, only: [:show, :edit, :update]
  post 'plofile', to: 'plofiles#update'
  get 'users', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'read/:id', to: 'notification_reads#create', as: 'read'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :tasks
  has_many :notifications
  has_many :members
  accepts_nested_attributes_for :members, allow_destroy: true

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/label.rb
class Label < ApplicationRecord
end

app/models/lavel.rb
class Lavel < ApplicationRecord
  has_many :task_lavels
  has_many :tasks, through: :task_lavels
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
  
  enum role: { member: 1, manager: 2 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :task
  belongs_to :group

  enum term: { green: 0, yellow: 1, red: 2 }
  enum read: { yet: 0, done: 1 }

  def kidoku
    update(read: 1)
  end

  private

  def self.notification_management
    notifications = Notification.all
    notifications.each do |notification|
      #Notificationにあるタスクのうち、完了になったものは消す
      if notification.task.completed?
        notification.delete
        return
      end
      #期限が3日以内の場合:黄色
      if Time.current <= notification.task.term && notification.task.term < Time.current.since(3.days)
        notification.update(term: 1)
      #期限が過ぎている場合:赤
      elsif notification.task.term < Time.current
        notification.update(term: 2)
      #それ以外の場合（黄色or赤だったが、期限が延びた場合はお知らせから消す）
      else
        notification.delete
      end
    end
  end

  def self.set_notification
    self.notification_management
    # termがnilではないもの、且つ’完了’ではないタスクを呼び出す
    tasks = Task.where.not(term: nil, status: 2)
    tasks.each do |task|
      # タスクの期限が3日以内だった場合
      #byebug
      if Time.current <= task.term && task.term < Time.current.since(3.days)
        notification = Notification.find_or_create_by(task_id: task.id, group_id: task.group_id)
        notification.update(term: 1)
        NotificationMailer.notification_email(task.user, task).deliver_later
      # 期限が過ぎていた場合
      elsif task.term < Time.current
        notification = Notification.find_or_create_by(task_id: task.id, group_id: task.group_id)
        notification.update(term: 2)
      end
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :task_tags
  has_many :tasks, through: :task_tags
end

app/models/task.rb
class Task < ApplicationRecord
  include RankedModel
  ranks :row_order, :class_name => 'Task', :with_same => :group_id

  belongs_to :user
  belongs_to :group
  has_one :notification, dependent: :destroy
  has_many :task_lavels, dependent: :destroy
  has_many :lavels, through: :task_lavels

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 200 }

  enum status: { waiting: 0, warking: 1, completed: 2 }
  enum priority: { low: 0, middle: 1, high: 2 }

  mount_uploader :image, ImageUploader

  def save_lavels(lavels)
    lavels = [] if lavels.nil?
    current_lavels = self.lavels.pluck(:body) unless self.lavels.nil?
    old_lavels = current_lavels - lavels
    new_lavels = lavels - current_lavels

    old_lavels.each do |old_lavel_name|
      self.lavels.delete(Lavel.find_by(body: old_lavel_name))
    end

    new_lavels.each do |new_lavel_name|
      task_label = Lavel.find_or_create_by(body: new_lavel_name)
      self.lavels << task_label
    end
  end
end

app/models/task_lavel.rb
class TaskLavel < ApplicationRecord
  belongs_to :task
  belongs_to :lavel
end

app/models/task_tag.rb
class TaskTag < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :members, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  enum role: { member: 0, admin: 1 }

  has_secure_password

  before_destroy :count_admin_user_for_destroy
  before_update :count_admin_user_for_edit

  mount_uploader :avatar, AvatarUploader

  def count_admin_user_for_destroy
    if User.all.admin.count == 1 && admin?
      errors.add :base, ''
      throw :abort
    end
  end

  def count_admin_user_for_edit
    if User.all.admin.count == 1 && role_changed?(from: 'admin', to: 'member')
      errors.add :base, ''
      throw :abort
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  before_action :set_autocomplete_tag, only: %i[new edit]
  before_action :set_lavel_list, only: %i[create update]
  before_action :set_group, only: %i[new create]
  before_action :require_user_logged_in

  def index
    @search = @current_user.tasks.ransack(params[:q])
    @tasks = @search.result.page(params[:page]).per(10)
    @notifications = @current_user.notifications.includes(:task)
  end

  def new
    @task = @group.tasks.build
  end

  def create
    @task = @group.tasks.build(task_params)
    @task.user_id = @current_user.id
    if @task.save && @task.save_lavels(@lavels)
      flash[:success] = t('.succsess')
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def edit
    gon.lavels = @task.lavels.pluck(:body)
  end

  def update
    @group = Group.find(@task.group_id)
    if @task.update(task_params) && @task.save_lavels(@lavels)
      flash[:succsess] = t('.edit')
      redirect_to group_path(@group)
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @group = Group.find(@task.group_id)
    if @task.destroy
      flash[:success] = t('.delete')
      redirect_to group_path(@group)
    else
      flash[:danger] = t('.delete-faild')
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :description, :term, :status, :priority, :image, :image_cache, :remove_image )
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def set_lavel_list
    @lavels = params[:lavels]
  end

  def set_autocomplete_tag
    gon.availavle_tags = Lavel.pluck(:body)
  end

  def set_group
    @group = current_user.members.where(group_id: params[:group_id]).first.group
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calender_helper.rb
module CalenderHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def be_in_group?
    @group.members.exists?(user_id: current_user.id)
  end
end

app/helpers/plofile_helper.rb
module PlofileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_url(user, options = {size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/tasks/_drop.html.slim
.dropdown
  .dropdown-trigger
    button.button.alert-button aria-controls="dropdown-menu" aria-haspopup="true"
      -if @notifications.count >= 1
        span =fa_icon("bell 2x",class: 'alert-active')
      -else
        span =fa_icon("bell-slash 2x", class: 'alert-non-active')
  - if @notifications.count >= 1
    #dropdown-menu.dropdown-menu role="menu"
      .dropdown-content
        - @notifications.each do |notification|
          =render partial: 'notification_reads/notification_item', locals: {notification: notification}

app/views/tasks/_form.html.slim
.field
  =form_with model:task, url: group_tasks_path, :builder => CustomFormBuilder, local: true do |f|
    .field
      .control
        =f.label t('.lavel'), class: 'label'
        ul#task_lavels
    .field
      =f.label :title, t('.title'), class: 'label'
      .control
        =f.text_field :title, placeholder: "ToDo Title", value: task.title, class: 'input'
    .field
      =f.file_field :image, id: 'post_image'
      =f.hidden_field :image_cache
      div.photo-area
        img#preview.preview-size.hidden src=""
    .field
      =f.check_box :remove_image
      span =t('.delete-image')
      =f.label :description, t('.description'), class: 'label'
      .control
        =f.text_field :description, placeholder: "Description", value: task.description, class: 'input'
    .field
      =f.label :term, t('.limit'), class: 'label'
      .control
        =f.date_field :term, class:'custom-date_field'
    .field.is-grouped
      .control=f.label :status, t('activerecord.attributes.task.status'), class: 'label-position-down'
      .select.control
        =f.select :status, Task.statuses.map{ |key, val| [Task.statuses_i18n[key],key] }
      .control=f.label :priority, t('activerecord.attributes.task.priority'),class: 'label-position-down'
      .select.control
          =f.select :priority, Task.priorities.map{ |key, val| [Task.priorities_i18n[key],key] }
    .field
      .control
        =f.submit class: 'button is-primary'

app/views/tasks/_search_form.html.slim
  =search_form_for search, url: group_path(group_id: @group.id),  class:'field is-grouped' do |f|
    p.control=f.search_field :title_or_lavels_body_cont, class: 'input ',placeholder: 'タイトルorタグ検索'
    p.control=f.select :status_eq, Task.statuses.map{ |key, val| [Task.statuses_i18n[key], val] },{include_blank: 'すべて'}, class:'select control'
    p.control=f.submit '検索', class: 'control button is-info'

app/views/tasks/edit.html.slim
.field
  =form_with model:@task, :builder => CustomFormBuilder, local: true do |f|
    .field
      .control
        =f.label t('tasks.form.lavel'), class: 'label'
        ul#task_lavels
    .field
      =f.label :title, t('tasks.show.title'), class: 'label'
      .control
        =f.text_field :title, placeholder: "ToDo Title", value: @task.title, class: 'input'
    .field
      =f.file_field :image, id: 'post_image'
      =f.hidden_field :image_cache
      div.photo-area
        - if @task.image?
          .uploaded-image=image_tag @task.image.url
        img#preview.preview-size.hidden src=""
    .field
      =f.check_box :remove_image
      span =t('tasks.form.delete-image')
    .field
      =f.label :description, t('tasks.show.description'), class: 'label'
      .control
        =f.text_field :description, placeholder: "Description", value: @task.description, class: 'input'
    .field
      =f.label :term, t('tasks.index.term'), class: 'label'
      .control
        =f.date_field :term, class:'custom-date_field'
    .field.is-grouped
      .control=f.label :status, t('activerecord.attributes.task.status'), class: 'label-position-down'
      .select.control
        =f.select :status, Task.statuses.map{ |key, val| [Task.statuses_i18n[key],key] }
      .control=f.label :priority, t('activerecord.attributes.task.priority'),class: 'label-position-down'
      .select.control
          =f.select :priority, Task.priorities.map{ |key, val| [Task.priorities_i18n[key],key] }
    .field
      .control
        =f.submit class: 'button is-primary'

app/views/tasks/index.html.slim
div.content
  div.columns
    div.column
      h1=t('.title')
      =link_to t('.new'), new_task_path, class: 'button is-primary'
    div.column
      =render 'drop', { notifications: @notifications }
  div.columns
  =render 'search_form', { search: @search }
  .columns
    .column.is-3.is-offset-9=paginate @tasks
  .columns
    .column
      table.table.is-striped
        thead
          tr
            th =t('tasks.show.title')
            th =t('tasks.show.description')
            th =sort_link(@search, :term, t('.term'))
            th =sort_link(@search, :created_at, t('.created_at'),default_order: :asc)
            th =t('activerecord.attributes.task.status')
            th =sort_link(@search, :priority, t('activerecord.attributes.task.priority'))
            th
            th
        tbody
          - @tasks.each do |task|
            tr
              td =link_to task.title, task_path(task)
              td =task.description
              td =task.term
              td =l(task.created_at, format: :default)
              td =t(Task.statuses_i18n[task.status])
              td =t(Task.priorities_i18n[task.priority])
              td =link_to t('.edit'), edit_task_path(task)
              td =link_to t('.delete'), task_path(task),method: :delete, data: {confirm: '削除しますか？'}
  .columns
    .column.is-3.is-offset-9=paginate @tasks
  .columns
    .column

app/views/tasks/new.html.slim
div
  =render 'form', {task: @task}

app/views/tasks/show.html.slim
.content
  .columns
    .column
      .subtitle.is-5
        h3= @task.title
      h4 =t('.description')
      p= @task.description
      = link_to t('.back'), root_path
    .column
      -unless @task.image.file.nil?
        =image_tag @task.image.url