config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  mount Sidekiq::Web, at: "/sidekiq"


  get 'calender/index'
  ActiveAdmin.routes(self)
  namespace :admin do
    resource :graphs, only: [:show]
  end
  root to: 'groups#index'
  get 'signup', to: 'users#new'
  #resources :tasks
  resources :users, only: [:new, :create]
  resources :groups, shallow: true do
    resources :tasks
    resources :custom_task_lists, only: [:index] do
      put :sort
    end
    resources :members
    resources :calenders, only: [:index]
  end
  resource :plofile, only: [:show, :edit, :update]
  post 'plofile', to: 'plofiles#update'
  get 'users', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'read/:id', to: 'notification_reads#create', as: 'read'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :tasks
  has_many :notifications
  has_many :members
  accepts_nested_attributes_for :members, allow_destroy: true

  validates :name, presence: true, length: { maximum: 50 }
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/label.rb
class Label < ApplicationRecord
end

app/models/lavel.rb
class Lavel < ApplicationRecord
  has_many :task_lavels
  has_many :tasks, through: :task_lavels
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :group
  belongs_to :user
  
  enum role: { member: 1, manager: 2 }
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :task
  belongs_to :group

  enum term: { green: 0, yellow: 1, red: 2 }
  enum read: { yet: 0, done: 1 }

  def kidoku
    update(read: 1)
  end

  private

  def self.notification_management
    notifications = Notification.all
    notifications.each do |notification|
      #Notificationにあるタスクのうち、完了になったものは消す
      if notification.task.completed?
        notification.delete
        return
      end
      #期限が3日以内の場合:黄色
      if Time.current <= notification.task.term && notification.task.term < Time.current.since(3.days)
        notification.update(term: 1)
      #期限が過ぎている場合:赤
      elsif notification.task.term < Time.current
        notification.update(term: 2)
      #それ以外の場合（黄色or赤だったが、期限が延びた場合はお知らせから消す）
      else
        notification.delete
      end
    end
  end

  def self.set_notification
    self.notification_management
    # termがnilではないもの、且つ’完了’ではないタスクを呼び出す
    tasks = Task.where.not(term: nil, status: 2)
    tasks.each do |task|
      # タスクの期限が3日以内だった場合
      #byebug
      if Time.current <= task.term && task.term < Time.current.since(3.days)
        notification = Notification.find_or_create_by(task_id: task.id, group_id: task.group_id)
        notification.update(term: 1)
        NotificationMailer.notification_email(task.user, task).deliver_later
      # 期限が過ぎていた場合
      elsif task.term < Time.current
        notification = Notification.find_or_create_by(task_id: task.id, group_id: task.group_id)
        notification.update(term: 2)
      end
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :task_tags
  has_many :tasks, through: :task_tags
end

app/models/task.rb
class Task < ApplicationRecord
  include RankedModel
  ranks :row_order, :class_name => 'Task', :with_same => :group_id

  belongs_to :user
  belongs_to :group
  has_one :notification, dependent: :destroy
  has_many :task_lavels, dependent: :destroy
  has_many :lavels, through: :task_lavels

  validates :title, presence: true, length: { maximum: 50 }
  validates :description, length: { maximum: 200 }

  enum status: { waiting: 0, warking: 1, completed: 2 }
  enum priority: { low: 0, middle: 1, high: 2 }

  mount_uploader :image, ImageUploader

  def save_lavels(lavels)
    lavels = [] if lavels.nil?
    current_lavels = self.lavels.pluck(:body) unless self.lavels.nil?
    old_lavels = current_lavels - lavels
    new_lavels = lavels - current_lavels

    old_lavels.each do |old_lavel_name|
      self.lavels.delete(Lavel.find_by(body: old_lavel_name))
    end

    new_lavels.each do |new_lavel_name|
      task_label = Lavel.find_or_create_by(body: new_lavel_name)
      self.lavels << task_label
    end
  end
end

app/models/task_lavel.rb
class TaskLavel < ApplicationRecord
  belongs_to :task
  belongs_to :lavel
end

app/models/task_tag.rb
class TaskTag < ApplicationRecord
  belongs_to :task
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :members, dependent: :destroy

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

  enum role: { member: 0, admin: 1 }

  has_secure_password

  before_destroy :count_admin_user_for_destroy
  before_update :count_admin_user_for_edit

  mount_uploader :avatar, AvatarUploader

  def count_admin_user_for_destroy
    if User.all.admin.count == 1 && admin?
      errors.add :base, ''
      throw :abort
    end
  end

  def count_admin_user_for_edit
    if User.all.admin.count == 1 && role_changed?(from: 'admin', to: 'member')
      errors.add :base, ''
      throw :abort
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user_be_in_group, only: [:show, :edit, :update, :destroy]
  def index
    @members = @current_user.members.includes(:group)
    set_groups
  end

  def new
    @group = @current_user.groups.build
  end

  def create
    @group = @current_user.groups.build(group_params)
    if @group.save && @current_user.groups << @group
      @group.members.create(role: 2, user_id: @current_user.id)
      flash[:success] = t('.success')
      redirect_to controller: 'groups', action: 'index'
    else
      flash.now[:danger] = t('.danger')
      render 'new'
    end
  end

  def show
    @search = @group.tasks.ransack(params[:q])
    @tasks = @search.result.includes(:user).page(params[:page]).per(10)
    @notifications = @group.notifications.includes(:task)
  end

  def edit
  end

  def update
  end

  def destroy
    if @group.destroy
      flash[:success] = t('.delete')
      redirect_to action: 'index'
    else
      flash.now[:danger] = t('.delete-faild')
      render new
    end
  end

  private
  def group_params
    params.require(:group).permit(:name)
  end

  def set_group
    @group = @current_user.members.where(group_id: params[:id]).first.group
  end

  def set_groups
    @groups = @members.map { |member| member.group }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calender_helper.rb
module CalenderHelper
end

app/helpers/graphs_helper.rb
module GraphsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/members_helper.rb
module MembersHelper
  def be_in_group?
    @group.members.exists?(user_id: current_user.id)
  end
end

app/helpers/plofile_helper.rb
module PlofileHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_url(user, options = {size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/groups/edit.html.slim
h1 Groups#edit
p Find me in app/views/groups/edit.html.slim

app/views/groups/index.html.slim
.content
  .columns
    .column
      h1=t('.title')
      =link_to t('.new'), new_group_path, class: 'button is-primary'
    .column
  .columns
  .columns
    .column
  .columns
    .column
      -unless @groups.nil?
        table.table.is-striped
          thead
            tr
              th =t('.name')
              th =t('.member')
              th =t('.delete')
          tbody
            - @groups.each do |group|
              tr
                td =link_to group.name, group_path(group)
                td =group.members.count
                td =link_to fa_icon("trash 2x"), group_path(group), method: :delete,data: {confirm: 'いいんすか？'}
      -else
        div
          p まだグループに参加していません！新しくグループを作成するか、招待してもらいましょう！

app/views/groups/new.html.slim
.field
  =form_with model:@group, url: groups_path, local: true do |f|
    .field
      .control
        =f.label :name, t('.name'), class: 'label'
        .control
          =f.text_field :name, placeholder: t('.name'),class: 'input'
    .field
      .control
        =f.submit class: 'button is-primary'

app/views/groups/show.html.slim
div.content
  div.columns
    div.column
      h1= @group.name
      =link_to t('.new'), new_group_task_path(group_id: @group.id), class: 'button is-primary'
    div.column
      =render 'tasks/drop', { notifications: @notifications }
      =link_to t('.member'), group_members_path(group_id: @group.id), class: 'button is-success'
      =link_to t('.calender'), group_calenders_path(group_id: @group.id), class: 'button is-primary calender'
  div.columns
  =render 'tasks/search_form', { search: @search }
  .columns
    .column.is-3.is-offset-9=paginate @tasks
  .columns
    .column
      table.table.is-striped
        thead
          tr
            th =t('tasks.show.title')
            th =t('.creater')
            th =sort_link(@search, :term, t('.term'))
            th =sort_link(@search, :created_at, t('.created_at'),default_order: :asc)
            th =t('activerecord.attributes.task.status')
            th =sort_link(@search, :priority, t('activerecord.attributes.task.priority'))
            th
            th
        tbody
          - @tasks.each do |task|
            tr
              td =link_to task.title, task_path(task)
              td =task.user.name
              td =task.term
              td =l(task.created_at, format: :default)
              td =t(Task.statuses_i18n[task.status])
              td =t(Task.priorities_i18n[task.priority])
              td =link_to t('.edit'), edit_task_path(task)
              td =link_to t('.delete'), task_path(task),method: :delete, data: {confirm: '削除しますか？'}
  .columns
    .column.is-3.is-offset-9=paginate @tasks
  .columns
    .column